<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NamaObatSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nama_obat')->insert([
            [
                'kode_obat' => 'MED-001',
                'nama_obat' => 'Acethylsisteine capsule',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '1',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-002',
                'nama_obat' => 'Acyclovir 400 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-003',
                'nama_obat' => 'Acyclovir Cream',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '3',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-004',
                'nama_obat' => 'Albendazole Tab',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-005',
                'nama_obat' => 'Allopurinol 100 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-006',
                'nama_obat' => 'Ambroxol Tab',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-007',
                'nama_obat' => 'Aminophylline 200 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-008',
                'nama_obat' => 'Aminophylline injeksi',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '4',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-009',
                'nama_obat' => 'Amlodipin 5 mg / 10 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-010',
                'nama_obat' => 'Amoksisilin 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-011',
                'nama_obat' => 'Amoksisilin sirup kering 125 mg/5 ml',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-012',
                'nama_obat' => 'Antasida DOEN Tablet Kombinasi',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-013',
                'nama_obat' => 'Antasida Syrup',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-014',
                'nama_obat' => 'Anti Bakteri Cream / Bacitrasin Cream',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '3',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-015',
                'nama_obat' => 'Anti Fungi Salep / Salep Whitefid',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '3',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-016',
                'nama_obat' => 'Anti Hemoroid Supp',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '6',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-017',
                'nama_obat' => 'Asam Acetyl Selisilat 100 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-018',
                'nama_obat' => 'Asam Askorbat (Vit.C) tablet 50 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-019',
                'nama_obat' => 'Asam Mefenamat 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '10',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-020',
                'nama_obat' => 'Betametason krim 0,1%',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '3',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-021',
                'nama_obat' => 'Bromhexine Tab',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-022',
                'nama_obat' => 'Deksametason Tablet 0,5 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-023',
                'nama_obat' => 'Deksametason injeksi',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '4',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-024',
                'nama_obat' => 'Difenhidramin HCI inj. 10 mg/ml - 1 ml',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '04',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-025',
                'nama_obat' => 'Dimenhidrinat 50 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-026',
                'nama_obat' => 'Domperidone',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-027',
                'nama_obat' => 'Erytromysin 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '10',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-028',
                'nama_obat' => 'Etanol 70%',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-029',
                'nama_obat' => 'Fenol Gliseron Tetestelinga 10%',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-030',
                'nama_obat' => 'Fitomenadion (Vit.K1) injeksi 10 mg/ml - 1 ml',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '4',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-031',
                'nama_obat' => 'Fitomenadion (Vit.K1) tablet salut gula 10 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-032',
                'nama_obat' => 'Furosemid Tablet 40 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-033',
                'nama_obat' => 'Garam Oralit untuk 200 ml air',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '7',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-034',
                'nama_obat' => 'Glibenklamide 5 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-035',
                'nama_obat' => 'Glimepiride 1 mg / 2 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-036',
                'nama_obat' => 'Gliseril Guayakolat tablet 100 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-037',
                'nama_obat' => 'Glukosa Larutan Infus 5% Steril (Produk Lokal)',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-038',
                'nama_obat' => 'Haloperidol tablet 5 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-039',
                'nama_obat' => 'Hidrokortison krim 2,5%',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '3',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-040',
                'nama_obat' => 'Ibuproden tablet 200mg / 400 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-041',
                'nama_obat' => 'Isosorbid Dinitrat Tablet Sublingual 5 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-042',
                'nama_obat' => 'Kalsium Laktat (Kalk) Tablet 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-043',
                'nama_obat' => 'Kaptopril 12,5 mg / 25 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-044',
                'nama_obat' => 'Ketokonazol 200 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-045',
                'nama_obat' => 'Kloramfenikol kapsul 250 mg/ 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '11',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-046',
                'nama_obat' => 'Kloramfenikol Syrup',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-047',
                'nama_obat' => 'Kloramfenikol Tetes Mata 0,5%',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-048',
                'nama_obat' => 'Kloramfenikol Tetes Telinga 3%',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-049',
                'nama_obat' => 'Klorfeniramin Maleat (CTM) tablet 4 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-050',
                'nama_obat' => 'Klorpromazin HCI Tablet Salut 100 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-051',
                'nama_obat' => 'Kotrimoksazol tab Dewasa 480 mg / 960 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-053',
                'nama_obat' => 'Lidokain Komp. Injeksi',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '4',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-054',
                'nama_obat' => 'Loratadin',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-055',
                'nama_obat' => 'Metamphyron / antalgin 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-056',
                'nama_obat' => 'Metoclopramid Tab',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-057',
                'nama_obat' => 'Metformin 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-058',
                'nama_obat' => 'Metilergometrin Maleat Tablet Salut 0,125 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-059',
                'nama_obat' => 'Metilergometrin Maleat tinj. 0,200 mg - 1 ml',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '4',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-060',
                'nama_obat' => 'Metronidazol tablet 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-061',
                'nama_obat' => 'Mikonazol Cream',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '3',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-062',
                'nama_obat' => 'Natrium Diklofenac 50 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-063',
                'nama_obat' => 'Natrium Clorida Infus (Pz)',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '9',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-064',
                'nama_obat' => 'Nistatin Vaginal Tablet',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '8',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-065',
                'nama_obat' => 'Obat batuk Hitam (O.B.H) Cairan',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-066',
                'nama_obat' => 'Oksitetrasiklin HCI Salep Kulit',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '3',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-067',
                'nama_obat' => 'Oksitetrasiklin HCI Salep Mata 1%',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '3',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-068',
                'nama_obat' => 'Oksitetrasiklin Injeksi 10 IU/ml - 1 ml',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '4',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-069',
                'nama_obat' => 'Parasetamol Sirup 120 mg / 5 ml',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-070',
                'nama_obat' => 'Parasetamol 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-071',
                'nama_obat' => 'Piridoksin HCL (Vit.B 6) Tablet 10 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-072',
                'nama_obat' => 'Povidon Iodida 10% 30 ml / 60 ml',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-073',
                'nama_obat' => 'Povidon iodida 10% 300 ml',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-074',
                'nama_obat' => 'Presnison Tablet 5 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-075',
                'nama_obat' => 'Ranitidine 150 mg tab',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-076',
                'nama_obat' => 'Ranitidine Injeksi',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '4',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-077',
                'nama_obat' => 'Ringer Laktat Larutan Infus Steril (Produk Lokal)',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-078',
                'nama_obat' => 'Salbutamol 2 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-079',
                'nama_obat' => 'Salep 2-4, Asam Salisilat 2% + Belerangendap...',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '12',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-080',
                'nama_obat' => 'Salisil Bedak 2%',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '13',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-081',
                'nama_obat' => 'Sianokobalamin (Vit. B 12) Injeksi 500mg - m...',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '4',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-082',
                'nama_obat' => 'Simvastain 10 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-083',
                'nama_obat' => 'Siprofoksasin 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-084',
                'nama_obat' => 'Tetrasiklin HCI Kapsul 250 mg / 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '14',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-085',
                'nama_obat' => 'Thiamphenikol 500 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '14',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-086',
                'nama_obat' => 'Tiamin HCI / Mononitrat (Vit. B 1) Tablet 50...',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-087',
                'nama_obat' => 'Triheksilfenidil Hidroklorida Tablet 2 mg',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-088',
                'nama_obat' => 'Vitamin B Komplex Tablet',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-089',
                'nama_obat' => 'Zinc Tablet',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-090',
                'nama_obat' => 'Attapulgit',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '2',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-091',
                'nama_obat' => 'Perhidrol',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '5',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-092',
                'nama_obat' => 'Alkohol Swab',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '15',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-093',
                'nama_obat' => 'Kapas 250 gram',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '16',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-094',
                'nama_obat' => 'Kasa Hidrofil 16 cm x 16 cm',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '17',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-095',
                'nama_obat' => 'Kasa Kompress 40 x 40 Steril',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '16',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-096',
                'nama_obat' => 'Kasa Pembalut 2 m x 80 cm',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '16',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-097',
                'nama_obat' => 'Kasa Pembalut 4 m x 15 cm',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '16',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-098',
                'nama_obat' => 'Kasa Pembalut 4 m x 3 cm',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '16',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_obat' => 'MED-099',
                'nama_obat' => 'Plester Coklat / Putih',
                'jenis_obat_id' => '1',
                'satuan_obat_id' => '16',
                'lokasi_penyimpanan' => 'Rak A1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
