<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PasienSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pasien')->insert([
            [
                'nama' => 'Bagas Satrio Wicaksono',
                'nik' => '3516080804030002',
                'alamat' => 'Mojokerto',
                'jenis_kelamin' => 'L',
                'golongan_darah' => 'A',
                'no_telepon' => '089672635263',
                'no_bpjs' => '012345',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Benediktus Arion',
                'nik' => '3516080703040003',
                'alamat' => 'Nganjuk',
                'jenis_kelamin' => 'L',
                'golongan_darah' => 'B',
                'no_telepon' => '089746325817',
                'no_bpjs' => '067233',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Citra Anindya Putri',
                'nik' => '3516083004030001',
                'alamat' => 'Denpasar',
                'jenis_kelamin' => 'P',
                'golongan_darah' => 'O',
                'no_telepon' => '089281767832',
                'no_bpjs' => '084672',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Azkia Alesha Humaira',
                'nik' => '3516083004030002',
                'alamat' => 'Surabaya',
                'jenis_kelamin' => 'P',
                'golongan_darah' => 'AB',
                'no_telepon' => '089672635299',
                'no_bpjs' => '087649',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Doni Hermawan',
                'nik' => '3516081505020001',
                'alamat' => 'Malang',
                'jenis_kelamin' => 'L',
                'golongan_darah' => 'O',
                'no_telepon' => '082145789632',
                'no_bpjs' => '098765',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Eka Suryani',
                'nik' => '3516082206040004',
                'alamat' => 'Blitar',
                'jenis_kelamin' => 'P',
                'golongan_darah' => 'B',
                'no_telepon' => '083847562914',
                'no_bpjs' => '065432',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fajar Pambudi',
                'nik' => '3516081103050003',
                'alamat' => 'Jombang',
                'jenis_kelamin' => 'L',
                'golongan_darah' => 'A',
                'no_telepon' => '081234567890',
                'no_bpjs' => '123456',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Gita Wijaya',
                'nik' => '3516083107020002',
                'alamat' => 'Kediri',
                'jenis_kelamin' => 'P',
                'golongan_darah' => 'AB',
                'no_telepon' => '087654321098',
                'no_bpjs' => '456789',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hendra Sutrisno',
                'nik' => '3516080908010001',
                'alamat' => 'Tuban',
                'jenis_kelamin' => 'L',
                'golongan_darah' => 'O',
                'no_telepon' => '082567891234',
                'no_bpjs' => '789012',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Indah Lestari',
                'nik' => '3516082405030004',
                'alamat' => 'Bojonegoro',
                'jenis_kelamin' => 'P',
                'golongan_darah' => 'B',
                'no_telepon' => '089345678901',
                'no_bpjs' => '234567',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Joko Susanto',
                'nik' => '3516081206020003',
                'alamat' => 'Lamongan',
                'jenis_kelamin' => 'L',
                'golongan_darah' => 'A',
                'no_telepon' => '081928374650',
                'no_bpjs' => '567890',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kirana Dewi',
                'nik' => '3516083008050002',
                'alamat' => 'Gresik',
                'jenis_kelamin' => 'P',
                'golongan_darah' => 'AB',
                'no_telepon' => '089876543210',
                'no_bpjs' => '890123',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Luki Pratama',
                'nik' => '3516081602040001',
                'alamat' => 'Sidoarjo',
                'jenis_kelamin' => 'L',
                'golongan_darah' => 'O',
                'no_telepon' => '082345678901',
                'no_bpjs' => '012346',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Maya Kusuma',
                'nik' => '3516082909010003',
                'alamat' => 'Pasuruan',
                'jenis_kelamin' => 'P',
                'golongan_darah' => 'B',
                'no_telepon' => '083456789012',
                'no_bpjs' => '345678',
                'status' => 'aktif',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
